---
# ----------------------------------------------------------------------------------------
# -- Docs: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker --
# ----------------------------------------------------------------------------------------
version: "3.6"

services:
  glue:
    # image: amazon/aws-glue-libs:glue_libs_2.0.0_image_01
    build: .
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
      - AWS_REGION=eu-central-1
    ports:
      - 4040:4040
      - 8888:8888
    volumes:
      - './notebooks:/home/glue_user/workspace/jupyter_workspace'
      - './jobs:/opt/jobs'
    command: /home/glue_user/jupyter/jupyter_start.sh
    links:
      - localstack

  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.aws:/docker-entrypoint-initaws.d'
      - '/var/run/docker.sock:/var/run/docker.sock'
...
